## Objective : Learning the process of comparing two classifiers

## Problem : Compare SVC with knn-classification with settings of your choice using bankruptcy data

## Step 1 : Data Preperation

In [2]:
import pandas as pd
df=pd.read_csv("bankruptcy.csv")
df

X1    X2    X3    X4  cl
0  -0.45 -0.41  1.09  0.45   0
1  -0.56 -0.31  1.51  0.16   0
2   0.06  0.02  1.01  0.40   0
3  -0.07 -0.09  1.45  0.26   0
4  -0.10 -0.09  1.56  0.67   0
5  -0.14 -0.07  0.71  0.28   0
6   0.04  0.01  1.50  0.71   0
7  -0.07 -0.06  1.37  0.40   0
8   0.07 -0.01  1.37  0.34   0
9  -0.14 -0.14  1.42  0.43   0
10 -0.23 -0.30  0.33  0.18   0
11  0.07  0.02  1.31  0.25   0
12  0.01  0.00  2.15  0.70   0
13 -0.28 -0.23  1.19  0.66   0
14  0.15  0.05  1.88  0.27   0
15  0.37  0.11  1.99  0.38   0
16 -0.08 -0.08  1.51  0.42   0
17  0.05  0.03  1.68  0.95   0
18  0.01  0.00  1.26  0.60   0
19  0.12  0.11  1.14  0.17   0
20 -0.28 -0.27  1.27  0.51   0
21  0.51  0.10  2.49  0.54   1
22  0.08  0.02  2.01  0.53   1
23  0.38  0.11  3.27  0.35   1
24  0.19  0.05  2.25  0.33   1
25  0.32  0.07  4.24  0.63   1
26  0.31  0.05  4.45  0.69   1
27  0.12  0.05  2.52  0.69   1
28 -0.02  0.02  2.05  0.35   1
29  0.22  0.08  2.35  0.40   1
30  0.17  0.07  1.80  0.52   1
31  0.15  0.05  2.17  0.55   1
32 -0.10 -0.01  2.50  0.58   1
33  0.14 -0.03  0.46  0.26   1
34  0.14  0.07  2.61  0.52   1
35  0.15  0.06  2.23  0.56   1
36  0.16  0.05  2.31  0.20   1
37  0.29  0.06  1.84  0.38   1
38  0.54  0.11  2.33  0.48   1
39 -0.33 -0.09  3.01  0.47   1
40  0.48  0.09  1.24  0.18   1
41  0.56  0.11  4.29  0.44   1
42  0.20  0.08  1.99  0.30   1
43  0.47  0.14  2.92  0.45   1
44  0.17  0.04  2.45  0.14   1
45  0.58  0.04  5.06  0.13   1

## Step 2 : Slicing of data and target

In [19]:
import numpy as np
X=df[["X1","X2","X3","X4"]] # data part
y=df[["cl"]] # target part
# X and y are data frames

# Step 3 : Importing SVC module and fitting for the given data

In [22]:
from sklearn.svm import SVC
clf = SVC(gamma='auto')
y=np.array(y) # convert y into an array
y_rs=y.reshape((46,)) # reshaped into one dimensional array
clf.fit(X, y)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [23]:
y_predicted=clf.predict(X)
y=np.array(y)
y_rs=y.reshape((-1,))

In [29]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int64)

In [27]:
y_predicted

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_rs,y_predicted)

array([[18,  3],
       [ 3, 22]], dtype=int64)

#  Step 4 : Getting the validity metrics for SVC

In [33]:
from sklearn import metrics
accuracy=metrics.accuracy_score(y_rs,y_predicted)
precision=metrics.precision_score(y_rs,y_predicted)
recall=metrics.recall_score(y_rs,y_predicted)
fscore=metrics.f1_score(y_rs,y_predicted)
print("\n The accuracy of support vector classifier is",np.round(100*accuracy,2),"%")
print("\n The precision of support vector classifier is",np.round(100*precision,2),"%")
print("\n The Recall of support vector classifier is",np.round(100*recall,2),"%")
print("\n The F-Score of support vector classifier is",np.round(100*fscore,2),"%")


 The accuracy of support vector classifier is 86.96 %

 The precision of support vector classifier is 88.0 %

 The Recall of support vector classifier is 88.0 %

 The F-Score of support vector classifier is 88.0 %


# Step 5: knn classification

In [34]:
from sklearn.neighbors import KNeighborsClassifier
k=8
clfk=KNeighborsClassifier(n_neighbors=k)
clfk.fit(X,y)
y_predk=clfk.predict(X)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


In [35]:
cnfknn=confusion_matrix(y_rs,y_predk)
cnfknn

array([[18,  3],
       [ 2, 23]], dtype=int64)

In [37]:
accuracy=metrics.accuracy_score(y_rs,y_predk)
precision=metrics.precision_score(y_rs,y_predk)
recall=metrics.recall_score(y_rs,y_predk)
fscore=metrics.f1_score(y_rs,y_predk)
print("\n The accuracy of k-nn classifier is",np.round(100*accuracy,2),"%")
print("\n The precision of k-nn classifier is",np.round(100*precision,2),"%")
print("\n The Recall of k-nn  is",np.round(100*recall,2),"%")
print("\n The F-Score of k-nn classifier is",np.round(100*fscore,2),"%")


 The accuracy of k-nn classifier is 89.13 %

 The precision of k-nn classifier is 88.46 %

 The Recall of k-nn  is 92.0 %

 The F-Score of k-nn classifier is 90.2 %


# Conclusions : Knn has more accuracy , 
# better precision, recall and F-score