In [1]:
from sklearn import datasets

In [2]:
digits = datasets.load_digits()

In [3]:
type(digits)

sklearn.utils._bunch.Bunch

In [4]:
X = digits.data 
Y = digits.target

In [5]:
type(X)

numpy.ndarray

In [6]:
digits.data.shape

(1797, 64)

In [7]:
from sklearn.decomposition import PCA
pca=PCA()
projected = pca.fit_transform(X)
print(digits.data.shape)
print(projected.shape)

(1797, 64)
(1797, 64)


In [8]:
print(projected)

[[-1.25946645e+00  2.12748835e+01 -9.46305462e+00 ... -0.00000000e+00
   0.00000000e+00  4.46141155e-14]
 [ 7.95761130e+00 -2.07686990e+01  4.43950604e+00 ... -3.43413308e-16
   1.98857230e-15  1.67046393e-16]
 [ 6.99192297e+00 -9.95598641e+00  2.95855808e+00 ... -2.81797505e-17
   1.04041405e-15  1.16654252e-16]
 ...
 [ 1.08012837e+01 -6.96025223e+00  5.59955453e+00 ...  2.36354366e-16
  -1.63831991e-16  9.70809841e-17]
 [-4.87210009e+00  1.24239536e+01 -1.01708664e+01 ...  1.05835778e-16
   4.60332024e-17 -1.23762878e-16]
 [-3.44389631e-01  6.36554919e+00  1.07737085e+01 ... -3.30709723e-17
  -1.47510643e-16  2.70670966e-16]]


In [9]:
pca.singular_values_

array([5.67006567e+02, 5.42251854e+02, 5.04630594e+02, 4.26117676e+02,
       3.53335033e+02, 3.25820366e+02, 3.05261580e+02, 2.81160331e+02,
       2.69069782e+02, 2.57823951e+02, 2.26318797e+02, 2.21514832e+02,
       1.98330715e+02, 1.95700139e+02, 1.77976271e+02, 1.74460791e+02,
       1.68727876e+02, 1.64158492e+02, 1.48233309e+02, 1.39831325e+02,
       1.38584433e+02, 1.31188207e+02, 1.28726917e+02, 1.24931590e+02,
       1.22575034e+02, 1.13444877e+02, 1.11480271e+02, 1.05463488e+02,
       1.02807802e+02, 9.62285662e+01, 8.98129647e+01, 8.73349465e+01,
       8.52596044e+01, 8.41567134e+01, 8.15893653e+01, 7.96420046e+01,
       7.44304714e+01, 7.01219569e+01, 6.92755923e+01, 6.75640682e+01,
       6.40331590e+01, 5.85269779e+01, 5.71281856e+01, 5.50924318e+01,
       5.01790999e+01, 4.81749428e+01, 4.56228649e+01, 4.08958572e+01,
       3.46850352e+01, 2.95461187e+01, 2.12889966e+01, 1.33446026e+01,
       1.06481402e+01, 1.04443771e+01, 8.44041164e+00, 5.18181553e+00,
      

In [10]:
pca.components_

array([[-1.77484909e-19, -1.73094651e-02, -2.23428835e-01, ...,
        -8.94184677e-02, -3.65977111e-02, -1.14684954e-02],
       [ 3.27805401e-18, -1.01064569e-02, -4.90849204e-02, ...,
         1.76697117e-01,  1.94547053e-02, -6.69693895e-03],
       [-1.68358559e-18,  1.83420720e-02,  1.26475543e-01, ...,
         2.32084163e-01,  1.67026563e-01,  3.48043832e-02],
       ...,
       [-0.00000000e+00, -2.43505756e-16,  9.08754362e-17, ...,
        -5.07750609e-17,  5.67069609e-17, -6.23244407e-17],
       [ 0.00000000e+00, -6.69329911e-16, -2.25828547e-17, ...,
        -9.50106071e-17,  1.10224249e-16, -1.88572194e-16],
       [ 1.00000000e+00, -1.68983002e-17,  5.73338351e-18, ...,
         8.66631300e-18, -1.57615962e-17,  4.07058917e-18]])

In [11]:
pca.explained_variance_

array([1.79006930e+02, 1.63717747e+02, 1.41788439e+02, 1.01100375e+02,
       6.95131656e+01, 5.91085249e+01, 5.18845391e+01, 4.40151067e+01,
       4.03109953e+01, 3.70117984e+01, 2.85190412e+01, 2.73211698e+01,
       2.19014881e+01, 2.13243565e+01, 1.76367222e+01, 1.69468639e+01,
       1.58513899e+01, 1.50044602e+01, 1.22344732e+01, 1.08868593e+01,
       1.06935663e+01, 9.58259779e+00, 9.22640260e+00, 8.69036872e+00,
       8.36561190e+00, 7.16577961e+00, 6.91973881e+00, 6.19295508e+00,
       5.88499123e+00, 5.15586690e+00, 4.49129656e+00, 4.24687799e+00,
       4.04743883e+00, 3.94340334e+00, 3.70647245e+00, 3.53165306e+00,
       3.08457409e+00, 2.73780002e+00, 2.67210896e+00, 2.54170563e+00,
       2.28298744e+00, 1.90724229e+00, 1.81716569e+00, 1.68996439e+00,
       1.40197220e+00, 1.29221888e+00, 1.15893419e+00, 9.31220008e-01,
       6.69850594e-01, 4.86065217e-01, 2.52350432e-01, 9.91527944e-02,
       6.31307848e-02, 6.07377581e-02, 3.96662297e-02, 1.49505636e-02,
      

In [12]:
import numpy as np
import matplotlib.pyplot as plt
pca = PCA().fit(digits.data)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance');

In [13]:
plt.scatter(projected[:, 0], projected[:, 1],c=digits.target)
plt.xlabel('component 1')
plt.ylabel('component 2')
plt.colorbar();

In [14]:
print(Y)

[0 1 2 ... 8 9 8]


In [15]:
import pandas as pd
X=pd.DataFrame(projected[:,1:11])

In [16]:
X.head()

0         1          2          3         4         5          6  \
0  21.274883 -9.463055  13.014189  -7.128823 -7.440659  3.252837   2.553470   
1 -20.768699  4.439506 -14.893664   5.896249 -6.485622  2.126228  -4.615936   
2  -9.955986  2.958558 -12.288302 -18.126023 -4.507664  1.843122 -16.415200   
3   3.332464  9.824372 -12.275838   6.965169  1.089483 -1.042085  10.973556   
4   4.269061 -5.675129 -13.851524  -0.358124 -2.857574 -0.720497  13.041696   

          7          8         9  
0 -0.581842   3.625697  2.585957  
1  3.587450  -1.074705 -5.385715  
2  0.719233   4.255805 -1.233374  
3 -3.259735   6.498753 -5.066853  
4 -3.835413  13.414164  2.673319

In [17]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
dfObj = pd.DataFrame(columns=['User_ID', 'UserName', 'Action'], index=['a', 'b', 'c'])
dfObj.loc['a'] = [23, 'Riti', 'Login']
dfObj.loc['b'] = [24, 'Aadi', 'Logout']
dfObj.loc['c'] = [25, 'Jack', 'Login']
print(dfObj)
for nrs in range(2, 6):
     knn = KNeighborsClassifier(n_neighbors=nrs)
     knn.fit(X, Y)
     Ypred=knn.predict(X)
     print("Accuracy:",metrics.accuracy_score(Y, Ypred))   
print ("over")     


  User_ID UserName  Action
a      23     Riti   Login
b      24     Aadi  Logout
c      25     Jack   Login
Accuracy: 0.9744017807456873
Accuracy: 0.9771841958820257
Accuracy: 0.9744017807456873
Accuracy: 0.9721758486366165
over


In [18]:
Ypred=knn.predict(X)

In [19]:
print(Ypred)

[0 1 2 ... 8 9 8]


In [20]:
Y

array([0, 1, 2, ..., 8, 9, 8])

In [21]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(Y, Ypred))

Accuracy: 0.9721758486366165


In [22]:
X1=X.iloc[:15,]
print(X1)

            0          1          2          3          4          5  \
0   21.274883  -9.463055  13.014189  -7.128823  -7.440659   3.252837   
1  -20.768699   4.439506 -14.893664   5.896249  -6.485622   2.126228   
2   -9.955986   2.958558 -12.288302 -18.126023  -4.507664   1.843122   
3    3.332464   9.824372 -12.275838   6.965169   1.089483  -1.042085   
4    4.269061  -5.675129 -13.851524  -0.358124  -2.857574  -0.720497   
5    7.914448   0.392494 -14.411096   8.484942 -10.863487  -1.412462   
6    5.288340  15.087405  -5.138381   4.581129  -4.362263   1.345093   
7  -21.071664 -12.282900  10.439277  -6.243046  12.747425  -8.551552   
8    1.183360   5.796257  -5.549540  -7.261641  -2.869018  -8.559843   
9    8.076324  -5.028084  -2.448339   3.288928  -0.775943  -4.548299   
10  16.919862 -10.066849   9.747088  -5.673415  -8.104378  -3.342633   
11 -11.994810 -14.131402 -28.090307   5.315725  -4.501819  -4.019540   
12  -4.851664  16.133972   1.167473   4.611619   3.409673  21.78

In [23]:
knn.predict(X1)

array([0, 1, 2, 3, 4, 9, 6, 7, 8, 9, 0, 1, 2, 3, 4])

In [24]:
Y[:15,]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4])